FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true

# Set the default editor and visual
ENV EDITOR=nano
ENV VISUAL=nano

# Install basic development tools
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  less \
  sudo \
  man-db \
  ripgrep \
  fzf \
  unzip \
  gnupg2 \
  jq \
  python3-pip \
  python3-setuptools \
  python3-wheel \
  python3-dev \
  wget \
  curl \
  gh \
  git \
  nano \
  micro \
  ncdu \
  htop \
  nvitop \
  screen \
  fontconfig \
  fonts-dejavu-core \
  libjpeg-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

#   magic-wormhole \

# Install uv (standalone Rust-based Python tool manager)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Install Node.js & Codex
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g @openai/codex@latest \
    && rm -rf /var/lib/apt/lists/*

# VSCode if needed
# curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz; tar -xf vscode_cli.tar.gz

# Create workspace and config directories and set permissions
RUN mkdir -p /workspace /root/.codex

WORKDIR /workspace
